### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by wqfdewifi** [jgcastro89/GenerativeDenseUNet#4]
Hi, Your work is very inspiring.
Do you mind tell me the evaluation metrics that you adopted and how about the perfermance/accuracy of your model？？

**Comment by jgcastro89** [comment]
Hi! I'm happy to hear that you find my work inspiring. As of now, I have only used class accuracy as the evaluation metric that is build into the MxNet framework (https://mxnet.apache.org/versions/1.6/api/python/docs/api/metric/index.html#mxnet.metric.Accuracy). I intend to add segmentation metrics to get a better description of model performance. I will likely stick to the same metrics used in the original paper (F3 Dataset) to have an "apples to apples" comparison. 

Model accuracy (using MxNet's built in metric) has varied, but I have achieved up to 92% accuracy on the validation dataset using this model.

**Comment by wqfdewifi** [comment]
Ok I see. Thank you for your answer！
